
services:
  backend: 
    build: .
    container_name: ecommerce-backend
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    depends_on:
      - db
    volumes:
      - .:/app
    command: sh -c "npm run migration:run && npm run start:prod"

  db:
    image: postgres:16
    container_name: ecommerce-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ecommerce 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecommerce-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  postgres_data:
