version: "3.8"

services:
  backend: 
    build: .
    container_name: nest-backend
    restart: always
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    command: npm run start:prod

postgres:
  image: postgres:15
  container_name: postgres-db
  restart: always
  environment:
    POSTGRES_USER: youruser
    POSTGRES_PASSWORD: yourpassword
    POSTGRES_DB: yourdb 
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  